In [1]:
from urllib.parse import urlencode, quote_plus, unquote
import requests
import json
import xmltodict
import pandas as pd

In [8]:
key = 'Emg92RIiy8Ga4Mdr8goOUBudAjLKq23eizbnPUNMASfIOKFpbj%2BG9tNZefK446evC4TVr1aHPkJYka1AlIHxdw%3D%3D'
url = f'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson?serviceKey={key}&'
queryParams = urlencode({ quote_plus('pageNo') : '1', quote_plus('numOfRows') : '10', quote_plus('startCreateDt') : '20200410', quote_plus('endCreateDt') : '20210410' })
res = requests.get(url + queryParams)
print(res)

<Response [200]>

In [9]:
# 문자열 XML을 JSON 형식으로 변환합니다.
res_json = xmltodict.parse(res.text) 
# 변환된 JSON 형식을 Dictionary 문자열로 변환합니다.
res_dict = json.dumps(res_json)     
# Dictionary 문자열을 파이썬의 Dictionary 형식으로 변환합니다.
data = json.loads(res_dict)
len(data['response']['body']['items']['item'])

6972

In [10]:
# df에 추가할 컬럼 리스트
createDt_list = []
deathCnt_list = []
defCnt_list = []
gubun_list = []
incDec_list = []
isolClearCnt_list = []
isolIngCnt_list = []
localOccCnt_list = []
overFlowCnt_list = []
qurRate_list = []
seq_list = []
stdDay_list = []
updateDt_list = []

In [11]:
# 컬럼 리스트에 값 추가, 값이 없는 경우 공백 추가
for i in range(len(data['response']['body']['items']['item'])):  
        try : createDt_list.append(data['response']['body']['items']['item'][i]['createDt'])
        except KeyError : createDt_list.append('')

        try : deathCnt_list.append(data['response']['body']['items']['item'][i]['deathCnt'])
        except KeyError : deathCnt_list.append('')

        try : defCnt_list.append(data['response']['body']['items']['item'][i]['defCnt'])
        except KeyError : defCnt_list.append('')

        try : gubun_list.append(data['response']['body']['items']['item'][i]['gubun'])
        except KeyError : gubun_list.append('')

        try : incDec_list.append(data['response']['body']['items']['item'][i]['incDec'])
        except KeyError : incDec_list.append('')

        try : isolClearCnt_list.append(data['response']['body']['items']['item'][i]['isolClearCnt'])
        except KeyError : isolClearCnt_list.append('')

        try : isolIngCnt_list.append(data['response']['body']['items']['item'][i]['isolIngCnt'])
        except KeyError : isolIngCnt_list.append('')

        try : localOccCnt_list.append(data['response']['body']['items']['item'][i]['localOccCnt'])
        except KeyError:localOccCnt_list.append('')

        try :  overFlowCnt_list.append(data['response']['body']['items']['item'][i]['overFlowCnt'])
        except KeyError:overFlowCnt_list.append('')

        try: qurRate_list.append(data['response']['body']['items']['item'][i]['qurRate'])
        except KeyError:qurRate_list.append('')

        try: seq_list.append(data['response']['body']['items']['item'][i]['seq'])
        except KeyError:seq_list.append('')

        try: stdDay_list.append(data['response']['body']['items']['item'][i]['stdDay'])
        except KeyError: stdDay_list.append('')

        try: updateDt_list.append(data['response']['body']['items']['item'][i]['updateDt'])
        except KeyError: updateDt_list.append('')

In [12]:
dataframe = pd.DataFrame()
dataframe['createDt'] = createDt_list
dataframe['deathCnt'] = deathCnt_list
dataframe['defCnt'] = defCnt_list
dataframe['gubun'] = gubun_list
dataframe['incDec'] = incDec_list
dataframe['isolClearCnt'] = isolClearCnt_list
dataframe['isolIngCnt'] = isolIngCnt_list
dataframe['localOccCnt'] = localOccCnt_list
dataframe['overFlowCnt'] = overFlowCnt_list
dataframe['qurRate'] = qurRate_list
dataframe['seq'] = seq_list
dataframe['stdDay'] = stdDay_list
dataframe['updateDt'] = updateDt_list
dataframe.to_excel('코로나 19 감염 시도 현황.xlsx', index=False)

In [13]:
dataframe

,createDt,deathCnt,defCnt,gubun,incDec,isolClearCnt,isolIngCnt,localOccCnt,overFlowCnt,qurRate,seq,stdDay,updateDt
0,2021-04-10 09:39:20.931,4,3227,검역,4,3087,136,0,4,-,8804,2021년 04월 10일 00시,null
1,2021-04-10 09:39:20.931,1,653,제주,7,621,31,7,0,97.35,8803,2021년 04월 10일 00시,null
2,2021-04-10 09:39:20.931,17,3157,경남,46,2903,237,44,2,93.92,8802,2021년 04월 10일 00시,null
3,2021-04-10 09:39:20.931,76,3672,경북,26,3394,202,26,0,137.92,8801,2021년 04월 10일 00시,null
4,2021-04-10 09:39:20.931,8,963,전남,7,891,64,7,0,51.64,8800,2021년 04월 10일 00시,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6967,2020-04-10 10:52:03.03,0,84,인천,0,31,53,0,0,2.84,962,2020년 4월 09일 00시,NULL
6968,2020-04-10 10:52:03.03,139,6807,대구,4,5106,1562,4,0,279.38,961,2020년 4월 09일 00시,NULL
6969,2020-04-10 10:52:03.03,3,125,부산,0,97,25,0,0,3.66,960,2020년 4월 09일 00시,NULL
6970,2020-04-10 10:52:03.03,2,590,서울,12,174,414,5,7,6.06,959,2020년 4월 09일 00시,NULL
6971,2020-04-10 10:52:03.03,204,10423,합계,39,6973,3246,16,23,20.10,958,2020년 4월 09일 00시,NULL